services:
  db:
    image: postgres:15-alpine
    container_name: devsync-db
    environment:
      POSTGRES_USER: devsync
      POSTGRES_PASSWORD: devsync
      POSTGRES_DB: devsync
    ports:
      - "5555:5432"
    volumes:
      - devsync_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsync"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./server
    container_name: devsync-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://devsync:devsync@db:5432/devsync?schema=public
      JWT_SECRET: supersecret_dev_only_change_me
      PORT: "5000"
      NODE_ENV: production
    ports:
      - "5000:5000"
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - "fetch('http://localhost:5000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  devsync_pgdata:
